version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: blog_db_prod
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-blog_db}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
    volumes:
      - prod_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: blog_be_prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - MYSQL_DATABASE=${DB_NAME:-blog_db}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    env_file:
      - ./backend/.env.prod
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: blog_nginx_prod
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  prod_db_data:
